services:
  comp3123-mongo:
    image: mongo:7
    container_name: comp3123-mongo
    environment:
      MONGO_INITDB_DATABASE: comp3123_db
    ports:
      - "27017:27017"
    volumes:
      - ./backend/mongo-data:/data/db

  comp3123-backend:
    build: ./backend
    container_name: comp3123-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - comp3123-mongo
    volumes:
    - ./backend/uploads:/app/uploads 

  comp3123-frontend:
    build: ./frontend
    container_name: comp3123-frontend
    ports:
      - "3001:3000"
    depends_on:
      - comp3123-backend

  comp3123-mongo-express:
    image: mongo-express
    container_name: comp3123-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: comp3123-mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - comp3123-mongo